app = "mercarol-celery"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
CELERY_BROKER_URL = "${CELERY_BROKER_URL}"
CELERY_RESULT_BACKEND = "${CELERY_RESULT_BACKEND}"
SECRET_KEY = "${SECRET_KEY}"
DATABASE_URL = "${DATABASE_URL}"


[deploy]
    release_command = "/bin/sh -c 'python manage.py collectstatic --noinput && python manage.py migrate'"


[processes]
  web = "gunicorn commerce.wsgi:application --bind 0.0.0.0:8000"
  worker = "celery -A commerce worker --loglevel=info"
  beat = "celery -A commerce beat --loglevel=info"


