"""
Django settings for commerce project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
from decouple import config
import os
import logging
from django.core.signals import got_request_exception
from django.dispatch import receiver
from django.core.wsgi import get_wsgi_application
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.core.management.utils import get_random_secret_key

SECRET_KEY = os.environ.get("SECRET_KEY", get_random_secret_key())

# Load local .env file
load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent



# Ensure logs folder exists (for local development)
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)



# SECRET_KEY = os.environ.get("SECRET_KEY")
# DEBUG = os.environ.get("DEBUG") == "True"

# ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ALLOWED_HOSTS = ["*"]



# DATABASES = {
#     "default": dj_database_url.parse(os.environ.get("DATABASE_URL"), conn_max_age=600)
# }

# staticfiles
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# app = get_wsgi_application()
# os.environ.setdefault("DJANGO_SETTINGS_MODULE", "commerce.settings")

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# Application definition

INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local apps
    "mercarol",

    # Third-party: Authentication & Users
    "djoser",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    # Third-party: Filters
    "django_filters",

    # Third-party: Serialization helpers
    "phonenumber_field",
    "django_countries",

    # Third-party: API Documentation
    "drf_spectacular",
    "drf_spectacular_sidecar",

    # Third-party: CORS
    "corsheaders",

    # Third-party: Developer tools
    "django_extensions",

    # Third-party: Celery
    "django_celery_results",
    "django_celery_beat",

    # staticfiles
    
]


SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
# LOGIN_REDIRECT_URL = "/api/schema/swagger-ui/"
# LOGOUT_REDIRECT_URL = "/accounts/login/"




MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
   
    # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
]

ROOT_URLCONF = "commerce.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "commerce.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     },

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': config('DB_NAME'),
    #     'USER': config('DB_USER'),
    #     'PASSWORD': config('DB_PASSWORD'),
    #     'HOST': config('DB_HOST'),
    #     'PORT': config('DB_PORT', default='5432'),
    #     'OPTIONS': {
    #         'sslmode': 'require',
    #     },
    # }


DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}

# DATABASES = {
#     "default": dj_database_url.parse(os.environ.get("DATABASE_URL"), conn_max_age=600)
# }

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# DATABASES = {
#     "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_ID_FIELD": "id",
    "USER_CREATE_PASSWORD_RETYPE": True,
    "SEND_ACTIVATION_EMAIL": False,                    # change to True later if needed

    "PASSWORD_RESET_CONFIRM_URL": "password/reset/confirm/{uid}/{token}",
    "ACTIVATION_URL": "activate/{uid}/{token}",

   "SERIALIZERS": {
        "user_create": "mercarol.serializers.CustomUserCreateSerializer",
        "user_create_password_retype": "mercarol.serializers.CustomUserCreateSerializer",  # ← THIS LINE IS THE KEY!
        "current_user": "mercarol.serializers.CustomUserSerializer",
        "user": "mercarol.serializers.CustomUserSerializer",
    },
}


AUTHENTICATION_BACKENDS = [
    "djoser.auth_backends.LoginFieldBackend",
]


# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = 'EMAIL_HOST_USER'



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
         
# Default User
AUTH_USER_MODEL = "mercarol.User"

# Rest_framework
REST_FRAMEWORK = {
    # DRF Schema
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Authentication: JWT for API
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Optional: SessionAuthentication if you want browser login
        "rest_framework.authentication.SessionAuthentication",
        'rest_framework.authentication.TokenAuthentication',
    ),

    # Permissions: require login by default
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}


# SPECTACULAR_SETTINGS = {
#     "TITLE": "Mercarol API – Marketplace & Auction System",
#     "DESCRIPTION": "API documentation for the MERCAROL Marketplace & Auction backend service",
#     "VERSION": "1.0.0",
#     "SERVE_INCLUDE_SCHEMA": False,

#     "SWAGGER_UI_DIST": "SIDECAR",
#     "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
#     "REDOC_DIST": "SIDECAR",

#     "COMPONENT_SPLIT_REQUEST": True,

#     "ENUMERATE_FIELD_CHOICES": True,
#     "ENUM_FIELD_LABEL_FORMAT": "{obj} (id: {pk})",

#     "ENUM_NAME_OVERRIDES": {
#         "mercarol.Order.status": "OrderStatusEnum",
#         "mercarol.Payment.status": "PaymentStatusEnum",
#         "mercarol.Payment.method": "PaymentMethodEnum",
#         "mercarol.Payment.vendor_payment_status": "VendorPaymentStatusEnum",
#         "mercarol.ShippingAddress.status": "ShippingStatusEnum",
#         "mercarol.Vendor.method": "VendorMethodEnum",
#         "mercarol.User.role": "UserRoleEnum",
#         "mercarol.AuctionItem.status": "AuctionItemStatusEnum",
#     }

# }



SPECTACULAR_SETTINGS = {
    "TITLE": "Mercarol API – Marketplace & Auction System",
    "DESCRIPTION": "API documentation for the MERCAROL Marketplace & Auction backend service",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,

    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",

    "COMPONENT_SPLIT_REQUEST": True,
    "ENUMERATE_FIELD_CHOICES": True,
    "ENUM_FIELD_LABEL_FORMAT": "{obj} (id: {pk})",

#     "ENUM_NAME_OVERRIDES": {
#     "OrderStatusEnum":       "mercarol.models.Order.status",
#     "PaymentStatusEnum":     "mercarol.models.Payment.status",
#     "PaymentMethodEnum":     "mercarol.models.Payment.method",
#     "UserRoleEnum":          "mercarol.models.User.role",
#     "AuctionItemStatusEnum": "mercarol.models.AuctionItem.status",
# }
}


# Django Cors Headers
CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)


# Redis settings
# Celery Configuration
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_BROKER_URL=os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True



CELERY_BEAT_SCHEDULE = {
    'update-auction-statuses': {
        'task': 'mercarol.tasks.update_auction_statuses',
        'schedule': crontab(minute='*/12'),
    },
    'ping_root_url': {
        'task': 'mercarol.tasks.ping_app',
        'schedule': crontab(minute='*/10'),
    },
}

# JWT settings 
SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


# LOGGING

# Ensure logs folder exists in development
if not os.getenv("RENDER"):
    os.makedirs(BASE_DIR / "logs", exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d",
        },
    },
    "handlers": {
        # Always log to console (stdout) – captured by Render
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if os.getenv("RENDER") else "verbose",
        },
        # Only write to file in development
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "mercarol.log",
            "formatter": "verbose",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"] + (["file"] if not os.getenv("RENDER") else []),
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"] + (["file"] if not os.getenv("RENDER") else []),
            "level": "INFO",
            "propagate": False,
        },
        "mercarol": {
            "handlers": ["console"] + (["file"] if not os.getenv("RENDER") else []),
            "level": "INFO",
            "propagate": False,
        },
    },
}


# settings.py → add at bottom
@receiver(got_request_exception)
def log_unhandled_exception(sender, request, **kwargs):
    logger = logging.getLogger('mercarol')
    logger.critical(f"Unhandled exception: {request.path}", exc_info=True)



ALLOWED_HOSTS = ["127.0.0.1",
                 "localhost",
                 "mercarol.onrender.com"]


ADMINS = [
    ('Mercarol', 'fomey81@gmail.com'),
]
DEFAULT_FROM_EMAIL = 'no-reply@mercarol.com'
