# Generated by Django 5.2.8 on 2025-11-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Images/products"),
        ),
    ]
