# Generated by Django 5.2.8 on 2025-11-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="name",
            new_name="receiver",
        ),
    ]
