# Generated by Django 5.2.8 on 2025-11-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
