# Generated by Django 5.2.8 on 2025-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0002_rename_name_shippingaddress_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="receiver",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="delivery_note",
            field=models.CharField(blank=True, max_length=526, null=True),
        ),
    ]
