# Generated by Django 5.2.8 on 2025-11-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0003_remove_shippingaddress_receiver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="Vendor_product",
            new_name="vendor_product",
        ),
    ]
