# Generated by Django 5.2.8 on 2025-11-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0003_alter_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="VendorProduct",
            new_name="vendor_product",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="reciever",
            new_name="receiver",
        ),
    ]
