# Generated by Django 5.2.8 on 2025-11-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0005_alter_productvariant_vendor_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="vendor_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant",
                to="mercarol.vendorproduct",
            ),
        ),
    ]
