# Generated by Django 5.2.8 on 2025-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0005_payment_delete_payement"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="vendor_payment_status",
            field=models.CharField(
                choices=[("PENDING", "pending"), ("DISBURSED", "disbursed")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
