# Generated by Django 5.2.8 on 2025-11-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0006_alter_productvariant_vendor_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="vendor",
            new_name="user",
        ),
    ]
