# Generated by Django 5.2.8 on 2025-11-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0007_rename_vendor_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction",
                to="mercarol.vendorproduct",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="coins",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
