# Generated by Django 5.2.8 on 2025-11-25 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0008_alter_auctionitem_product_alter_user_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
