# Generated by Django 5.2.8 on 2025-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0009_auctionitem_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
