# Generated by Django 5.2.8 on 2025-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0010_auctionitem_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorproduct",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
