# Generated by Django 5.2.8 on 2025-12-03 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercarol", "0011_vendorproduct_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedAuction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_auction_id", models.UUIDField(blank=True, null=True)),
                ("start_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "final_bid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mercarol.vendorproduct",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived Auction",
                "verbose_name_plural": "Archived Auctions",
                "ordering": ["-archived_at"],
            },
        ),
    ]
